[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "issue-prefix-pre-commit"
description = "adds issue number as a prefix to commit message"
version = "0.1.0"

[project.scripts]
add-issue-prefix = "hooks.add_issue_prefix:main"
